# Generated by Django 5.0.6 on 2024-05-31 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompraVendita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo', models.FloatField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Acquisto',
            fields=[
                ('compravendita_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestione.compravendita')),
            ],
            bases=('gestione.compravendita',),
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('compravendita_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestione.compravendita')),
            ],
            bases=('gestione.compravendita',),
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('compravendita_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestione.compravendita')),
            ],
            bases=('gestione.compravendita',),
        ),
        migrations.CreateModel(
            name='Vendita',
            fields=[
                ('compravendita_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestione.compravendita')),
            ],
            bases=('gestione.compravendita',),
        ),
    ]
