# Generated by Django 5.0.6 on 2024-05-30 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione', '0001_initial'),
        ('prodotto', '0001_initial'),
        ('utente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisto',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerta',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='prodotto.prodotto'),
        ),
        migrations.AddField(
            model_name='offerta',
            name='taglia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='prodotto.taglia'),
        ),
        migrations.AddField(
            model_name='offerta',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposta',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte', to='prodotto.prodotto'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='taglia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte', to='prodotto.taglia'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendita',
            name='banca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendite', to='utente.datibancari'),
        ),
        migrations.AddField(
            model_name='vendita',
            name='indirizzoFatturazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendite', to='utente.indirizzofatturazione'),
        ),
        migrations.AddField(
            model_name='vendita',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendite', to='prodotto.prodotto'),
        ),
        migrations.AddField(
            model_name='vendita',
            name='taglia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendite', to='prodotto.taglia'),
        ),
        migrations.AddField(
            model_name='vendita',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendite', to=settings.AUTH_USER_MODEL),
        ),
    ]
