# Generated by Django 5.0.6 on 2024-06-07 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_initial'),
        ('prodotto', '0001_initial'),
        ('utente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisto',
            name='carta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acquisti', to='utente.cartacredito'),
        ),
        migrations.AlterField(
            model_name='acquisto',
            name='indirizzoSpedizione',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acquisti', to='utente.indirizzospedizione'),
        ),
        migrations.AlterField(
            model_name='compravendita',
            name='prodotto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mercato', to='prodotto.prodotto'),
        ),
        migrations.AlterField(
            model_name='compravendita',
            name='taglia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mercato', to='prodotto.taglia'),
        ),
        migrations.AlterField(
            model_name='compravendita',
            name='utente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mercato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='carta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offerte', to='utente.cartacredito'),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='indirizzoSpedizione',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offerte', to='utente.indirizzospedizione'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='banca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proposte', to='utente.datibancari'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='indirizzoFatturazione',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proposte', to='utente.indirizzofatturazione'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='acquisto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='gestione.acquisto'),
        ),
        migrations.AlterField(
            model_name='vendita',
            name='banca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendite', to='utente.datibancari'),
        ),
        migrations.AlterField(
            model_name='vendita',
            name='indirizzoFatturazione',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vendite', to='utente.indirizzofatturazione'),
        ),
    ]
