# Generated by Django 5.0.6 on 2024-06-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='voto',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
