# Generated by Django 5.0.6 on 2024-06-07 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_alter_acquisto_carta_and_more'),
        ('prodotto', '0002_alter_taglia_offertamaggiore_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='compravendita',
            name='prodotto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercato', to='prodotto.prodotto'),
        ),
        migrations.AlterField(
            model_name='compravendita',
            name='taglia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mercato', to='prodotto.taglia'),
        ),
        migrations.AlterField(
            model_name='compravendita',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercato', to=settings.AUTH_USER_MODEL),
        ),
    ]
