# Generated by Django 5.0.6 on 2024-06-07 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0005_alter_compravendita_prodotto_and_more'),
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisto',
            name='carta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisti', to='utente.cartacredito'),
        ),
        migrations.AlterField(
            model_name='acquisto',
            name='indirizzoSpedizione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acquisti', to='utente.indirizzospedizione'),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='carta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerte', to='utente.cartacredito'),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='indirizzoSpedizione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerte', to='utente.indirizzospedizione'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='banca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposte', to='utente.datibancari'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='indirizzoFatturazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposte', to='utente.indirizzofatturazione'),
        ),
        migrations.AlterField(
            model_name='vendita',
            name='banca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendite', to='utente.datibancari'),
        ),
        migrations.AlterField(
            model_name='vendita',
            name='indirizzoFatturazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendite', to='utente.indirizzofatturazione'),
        ),
    ]
