# Generated by Django 5.0.6 on 2024-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_remove_recensione_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='voto',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
