# Generated by Django 5.0.6 on 2024-06-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_alter_acquisto_carta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisto',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Acquisti'},
        ),
        migrations.AlterModelOptions(
            name='offerta',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Offerte'},
        ),
        migrations.AlterModelOptions(
            name='proposta',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Proposte'},
        ),
        migrations.AlterModelOptions(
            name='recensione',
            options={'ordering': ['-acquisto__data'], 'verbose_name_plural': 'Recensioni'},
        ),
        migrations.AlterModelOptions(
            name='vendita',
            options={'ordering': ['-data'], 'verbose_name_plural': 'Vendite'},
        ),
    ]
