# Generated by Django 5.0.6 on 2024-05-27 20:06

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('prodotto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Uknown', max_length=25)),
                ('cognome', models.CharField(default='Uknown', max_length=25)),
                ('via', models.CharField(default='Uknown', max_length=50)),
                ('citta', models.CharField(default='Uknown', max_length=50)),
                ('cap', models.CharField(default='Uknown', max_length=5)),
                ('provincia', models.CharField(default='Uknown', max_length=2)),
                ('nazione', django_countries.fields.CountryField(max_length=2)),
                ('telefono', models.CharField(default='Uknown', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('nome', models.CharField(max_length=25)),
                ('cognome', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('dataNascita', models.DateField()),
                ('pIva', models.CharField(max_length=11)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CartaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Uknown', max_length=25)),
                ('cognome', models.CharField(default='Uknown', max_length=25)),
                ('numero', models.CharField(default='Uknown', max_length=16)),
                ('scadenza', models.DateField(default='Uknown')),
                ('cvv', models.CharField(default='Uknown', max_length=3)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatiBancari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Uknown', max_length=25)),
                ('cognome', models.CharField(default='Uknown', max_length=25)),
                ('iban', models.CharField(default='Uknown', max_length=27)),
                ('banca', models.CharField(default='Uknown', max_length=50)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dati', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndirizzoFatturazione',
            fields=[
                ('indirizzo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utente.indirizzo')),
            ],
            bases=('utente.indirizzo',),
        ),
        migrations.CreateModel(
            name='IndirizzoSpedizione',
            fields=[
                ('indirizzo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utente.indirizzo')),
            ],
            bases=('utente.indirizzo',),
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='prodotto.prodotto')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
