# Generated by Django 5.0.6 on 2024-05-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prodotto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=50)),
                ('citta', models.CharField(max_length=50)),
                ('cap', models.CharField(max_length=5)),
                ('provincia', models.CharField(max_length=2)),
                ('nazione', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('dataNascita', models.DateField()),
                ('pIva', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='IndirizzoFatturazione',
            fields=[
                ('indirizzo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utente.indirizzo')),
                ('titolo', models.CharField(max_length=50)),
            ],
            bases=('utente.indirizzo',),
        ),
        migrations.CreateModel(
            name='IndirizzoSpedizione',
            fields=[
                ('indirizzo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utente.indirizzo')),
                ('titolo', models.CharField(max_length=50)),
            ],
            bases=('utente.indirizzo',),
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzi', to='utente.utente'),
        ),
        migrations.CreateModel(
            name='CartaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('scadenza', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carte', to='utente.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='prodotto.prodotto')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='utente.utente')),
            ],
        ),
    ]
