# Generated by Django 5.0.6 on 2024-06-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartacredito',
            options={'verbose_name_plural': 'Carte di credito'},
        ),
        migrations.AlterModelOptions(
            name='datibancari',
            options={'verbose_name_plural': 'Dati bancari'},
        ),
        migrations.AlterModelOptions(
            name='indirizzofatturazione',
            options={'verbose_name_plural': 'Indirizzi di fatturazione'},
        ),
        migrations.AlterModelOptions(
            name='indirizzospedizione',
            options={'verbose_name_plural': 'Indirizzi di spedizione'},
        ),
        migrations.AlterModelOptions(
            name='utente',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='utente',
            name='immagineProfilo',
            field=models.ImageField(blank=True, null=True, upload_to='immaginiProfilo/'),
        ),
    ]
