# Generated by Django 5.0.6 on 2024-05-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='products',
            new_name='prodotto',
        ),
        migrations.AlterField(
            model_name='cartacredito',
            name='cognome',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='cartacredito',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cartacredito',
            name='nome',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='cartacredito',
            name='numero',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='datibancari',
            name='banca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datibancari',
            name='cognome',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='datibancari',
            name='iban',
            field=models.CharField(max_length=27),
        ),
        migrations.AlterField(
            model_name='datibancari',
            name='nome',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='cap',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='citta',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='cognome',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='nome',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='provincia',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='via',
            field=models.CharField(max_length=50),
        ),
    ]
