# Generated by Django 5.0.6 on 2024-06-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='prodotto',
            new_name='prodotti',
        ),
    ]
