# Generated by Django 5.0.6 on 2024-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotto', '0001_initial'),
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='dataNascita',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='pIva',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.CreateModel(
            name='createUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('dataNascita', models.DateField()),
                ('pIva', models.CharField(max_length=11)),
                ('via', models.CharField(max_length=50)),
                ('citta', models.CharField(max_length=50)),
                ('cap', models.CharField(max_length=5)),
                ('provincia', models.CharField(max_length=2)),
                ('nazione', models.CharField(max_length=50)),
                ('titolo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=16)),
                ('scadenza', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('products', models.ManyToManyField(to='prodotto.prodotto')),
            ],
        ),
    ]
