# Generated by Django 5.0.6 on 2024-05-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0003_alter_utente_datanascita_alter_utente_piva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indirizzofatturazione',
            name='titolo',
        ),
        migrations.RemoveField(
            model_name='indirizzospedizione',
            name='titolo',
        ),
        migrations.AddField(
            model_name='indirizzo',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
    ]
