# Generated by Django 5.0.6 on 2024-05-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0003_remove_cartacredito_scadenza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartacredito',
            name='scadenzaAnno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartacredito',
            name='scadenzaMese',
            field=models.IntegerField(),
        ),
    ]
