# Generated by Django 5.0.6 on 2024-05-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0004_remove_indirizzofatturazione_titolo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indirizzo',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
